/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dimorfismes;

import static java.lang.Math.exp;
import static java.lang.Math.log;
import static java.lang.Math.log10;
import static java.lang.Math.pow;
import java.text.DecimalFormat;

/**
 *
 * @author carles
 */
public class Interficie extends javax.swing.JFrame {

    /**
     * Creates new form Interficie
     */
    DecimalFormat dec = new DecimalFormat("0.00");
    int num = 0;
    //A,B
    double vlvA = 0;
    double vlvB = 0;
    double v1vA = 0;
    double v1vB = 0;
    double v2vA = 0;
    double v2vB = 0;
    //pendents
    double pl1 = 0;
    double pl2 = 0;
    double pv1 = 0;
    double pv2 = 0;
    double p12 = 0;
    //punts
    double lv1t = 0;
    double lv1p = 0;
    double lv2t = 0;
    double lv2p = 0;
    double l12t = 0;
    double l12p = 0;
    double v12t = 0;
    double v12p = 0;
    
    public Interficie() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel25 = new javax.swing.JLabel();
        panel = grafic.obteGrafic();
        titol = new javax.swing.JLabel();
        restart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xfrom = new javax.swing.JTextField();
        yfrom = new javax.swing.JTextField();
        change = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        xto = new javax.swing.JTextField();
        yto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lvlog = new javax.swing.JRadioButton();
        lvln = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lvA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lvB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lvent = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t1lv = new javax.swing.JTextField();
        dpdt1l = new javax.swing.JTextField();
        Add1l = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        t2lv = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dpdt2l = new javax.swing.JTextField();
        Add2l = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        t12v = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dpdt12 = new javax.swing.JTextField();
        Add12 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        v1log = new javax.swing.JRadioButton();
        v1ln = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        v1A = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        v1B = new javax.swing.JTextField();
        Add1V = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        v2A = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        v2B = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Add2V = new javax.swing.JButton();
        v2log = new javax.swing.JRadioButton();
        v2ln = new javax.swing.JRadioButton();
        info1lv = new javax.swing.JLabel();
        info2lv = new javax.swing.JLabel();
        info12l = new javax.swing.JLabel();
        info12v = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        t1lv1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        t2lv1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        t12v1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        t12v2 = new javax.swing.JTextField();
        log = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lin = new javax.swing.JButton();

        jLabel25.setText("jLabel25");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        titol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titol.setText("DIMORFISMS");

        restart.setText("Restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        jLabel3.setText("LV");

        jLabel4.setText("Change Range");

        change.setText("Set");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        jLabel5.setText("T");

        jLabel6.setText("P");

        lvlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvlogActionPerformed(evt);
            }
        });

        lvln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvlnActionPerformed(evt);
            }
        });

        jLabel1.setText("log p = A - B/T");

        jLabel2.setText("ln p = A - B/T");

        jLabel7.setText("A =");

        jLabel8.setText("B =");

        jLabel9.setText("P = [Pa] ; T = [K]");

        lvent.setText("Add");
        lvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lventActionPerformed(evt);
            }
        });

        jLabel10.setText("1L");

        jLabel11.setText("2L");

        jLabel12.setText("T1-l-v  =");

        jLabel13.setText("dp/dt =");

        Add1l.setText("Add");
        Add1l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1lActionPerformed(evt);
            }
        });

        jLabel14.setText("T2-l-v = ");

        jLabel15.setText("dp/dt = ");

        Add2l.setText("Add");
        Add2l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2lActionPerformed(evt);
            }
        });

        jLabel16.setText("12");

        jLabel19.setText("T1-2-v=");

        jLabel20.setText("dp/dt = ");

        Add12.setText("Add");
        Add12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add12ActionPerformed(evt);
            }
        });

        jLabel21.setText("1V");

        v1log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1logActionPerformed(evt);
            }
        });

        v1ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1lnActionPerformed(evt);
            }
        });

        jLabel22.setText("log p = A - B/T");

        jLabel23.setText("ln p = A - B/T");

        jLabel27.setText("P = [Pa] ; T = [K]");

        jLabel17.setText("A =");

        jLabel18.setText("B =");

        Add1V.setText("Add");
        Add1V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1VActionPerformed(evt);
            }
        });

        jLabel28.setText("log p = A - B/T");

        jLabel29.setText("ln p = A - B/T");

        jLabel30.setText("P = [Pa] ; T = [K]");

        jLabel31.setText("A =");

        jLabel32.setText("B =");

        jLabel33.setText("2V");

        Add2V.setText("Add");
        Add2V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2VActionPerformed(evt);
            }
        });

        v2log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2logActionPerformed(evt);
            }
        });

        v2ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2lnActionPerformed(evt);
            }
        });

        jLabel24.setText("T1-l-v  =");

        jLabel26.setText("T2-l-v  = ");

        jLabel34.setText("T1-2-v =");

        jLabel36.setText("T1-2-v =");

        log.setText("Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        jLabel35.setText("Change Scale");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lin.setLabel("Linear");
        lin.setMargin(new java.awt.Insets(2, 1, 2, 1));
        lin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel24))
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t1lv1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t12v1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel36))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t12v2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t2lv1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v1log)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v1ln)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel23))
                                            .addComponent(jLabel27))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Add1V, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel18))
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(v1B, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(v1A, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v2log)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v2ln)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel29))
                                            .addComponent(jLabel30))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Add2V, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel31)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(v2A, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel32)
                                                    .addGap(2, 2, 2)
                                                    .addComponent(v2B, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(xfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(yfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(xto)
                                                    .addComponent(yto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(info1lv)
                                    .addComponent(info2lv)
                                    .addComponent(info12l)
                                    .addComponent(info12v)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lvlog)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lvln)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel2)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lvent, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lvA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lvB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(1, 1, 1)
                                                .addComponent(t2lv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(t12v, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dpdt2l, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Add2l, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dpdt12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Add12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(1, 1, 1)
                                        .addComponent(t1lv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, 0)
                                        .addComponent(dpdt1l, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Add1l, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel19)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(titol)))
                .addGap(14, 14, 14)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lvlog, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addComponent(lvA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(lvB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lvln))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lvent)))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(t1lv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpdt1l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add1l))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(t2lv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(dpdt2l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add2l))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(t12v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(dpdt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(t1lv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(t12v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(v1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Add1V)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v1log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17)
                                        .addComponent(v1A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v1ln))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(t2lv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(t12v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(restart)
                                    .addComponent(info1lv))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(info2lv)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(info12l)
                                        .addGap(18, 18, 18)
                                        .addComponent(info12v))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(xfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(xto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(yfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(yto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(change))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(v2B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Add2V)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v2log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31)
                                        .addComponent(v2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v2ln)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(log)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //RESTART
    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
      //resetejar variables
        vlvA = 0;
        vlvB = 0;
        num = 0;
        pl1 = 0;
        pl2 = 0;
        p12 = 0;
        v1vA = 0;
        v1vB = 0;
        v2vA = 0;
        v2vB = 0;
        lv1t = 0;
        lv1p = 0;
        lv2t = 0;
        lv2p = 0;
        l12t = 0;
        l12p = 0;
        v12t = 0;
        v12p = 0;
      //resetejar botons
      //netejar text

      //resetejar grafic
        grafic.reset();
    }//GEN-LAST:event_restartActionPerformed

void recalcula(){
    //punt VAPOR-SOLID1-SOLID2
        if (v1vA != 0 && v2vA != 0 && v12t == 0) {
            if ((v1log.isSelected() && v2log.isSelected()) || (v1ln.isSelected() && v2ln.isSelected())){
                v12t = (v1vB-v2vB)/(v1vA-v2vA);
                if (v1log.isSelected()) v12p = pow(10,v1vA - v1vB/v12t);
                else v12p = exp(v1vA - v1vB/v12t); 
            }else if (v1log.isSelected() && v2ln.isSelected()){
                v12t = (v1vB*log(10)-v2vB)/(v1vA*log(10)-v2vA);
                v12p = exp(v2vA - v2vB/v12t);
            }else{
                v12t = (v1vB-v2vB*log(10))/(v1vA-v2vA*log(10));
                v12p = exp(v1vA - v1vB/v12t);
            }
            grafic.agregarPunt("v12", v12t, v12p);
            grafic.esPunt(num);
            ++num;
            info12v.setText("12V: T = " + String.valueOf(dec.format(v12t)) + " K, P = " + String.valueOf(dec.format(v12p)) + " Pa");
            recalcula();
        }
        //punt VAPOR-LIQUID-SOLID1
        else if (v1vA != 0 && vlvA != 0 && lv1t == 0) {
            if ((v1log.isSelected() && lvlog.isSelected()) || (v1ln.isSelected() && lvln.isSelected())){
                lv1t = (v1vB-vlvB)/(v1vA-vlvA);
                if (v1log.isSelected()) lv1p = pow(10,v1vA - v1vB/lv1t);
                else lv1p = exp(v1vA - v1vB/lv1t); 
            }else if (v1log.isSelected() && lvln.isSelected()){
                lv1t = (v1vB*log(10)-vlvB)/(v1vA*log(10)-vlvA);
                lv1p = exp(vlvA - vlvB/lv1t);
            }else{
                lv1t = (v1vB-vlvB*log(10))/(v1vA-vlvA*log(10));
                lv1p = exp(v1vA - v1vB/lv1t);
            }
            grafic.agregarPunt("lv1", lv1t, lv1p);
            grafic.esPunt(num);
            ++num;
            info1lv.setText("1LV: T = " + String.valueOf(dec.format(lv1t)) + " K, P = " + String.valueOf(dec.format(lv1p)) + " Pa");
            recalcula();
        }
        //punt VAPOR-LIQUID-SOLID2
        else if (vlvA != 0 && v2vA != 0 && lv2t == 0) {
            if ((lvlog.isSelected() && v2log.isSelected()) || (lvln.isSelected() && v2ln.isSelected())){
                lv2t = (vlvB-v2vB)/(vlvA-v2vA);
                if (lvlog.isSelected()) lv2p = pow(10,vlvA - vlvB/lv2t);
                else lv2p = exp(vlvA - vlvB/lv2t); 
            }else if (lvlog.isSelected() && v2ln.isSelected()){
                lv2t = (vlvB*log(10)-v2vB)/(vlvA*log(10)-v2vA);
                lv2p = exp(v2vA - v2vB/lv2t);
            }else{
                lv2t = (vlvB-v2vB*log(10))/(vlvA-v2vA*log(10));
                lv2p = exp(v2vA - v2vB/lv2t);
            }
            grafic.agregarPunt("lv2", lv2t, lv2p);
            grafic.esPunt(num);
            ++num;
            info2lv.setText("2LV: T = " + String.valueOf(dec.format(lv2t)) + " K, P = "+ String.valueOf(dec.format(lv2p))+ " Pa");
            recalcula();
        }
        //corba LÍQUID-VAPOR
        else if (lv1t != 0 && lv2t != 0 && vlvA == 0){
            lvln.setSelected(true);
            vlvB = (log(lv1p/lv2p))/((1/lv2t)-(1/lv1t));
            vlvA = log(lv1p) + vlvB/lv1t;
            lvA.setText(String.valueOf(vlvA));
            lvB.setText(String.valueOf(vlvB));
            String s = "e^(" + String.valueOf(vlvA) + " - " + String.valueOf(vlvB) + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(4, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("lv", x, y);
            grafic.esRecta(num);
            ++num;
            recalcula();
        }
        //corba VAPOR-SOLID1
        else if(v12t != 0 && lv1t != 0 && v1vA == 0){
            v1ln.setSelected(true);
            v1vB = (log(lv1p/v12p))/((1/v12t)-(1/lv1t));
            v1vA = log(lv1p) + v1vB/lv1t;
            v1A.setText(String.valueOf(v2vA));
            v1B.setText(String.valueOf(v2vB));
            String s = "e^(" + String.valueOf(v1vA) + " - " + String.valueOf(v1vB) + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(4, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("v1", x, y);
            grafic.esRecta(num);
            ++num;
            recalcula();
        }
        //corba VAPOR-SOLID2
        else if(v12t != 0 && lv2t != 0 && v2vA == 0){
            v2ln.setSelected(true);
            v2vB = (log(lv2p/v12p))/((1/v12t)-(1/lv2t));
            v2vA = log(lv2p) + v2vB/lv2t;
            v2A.setText(String.valueOf(v2vA));
            v2B.setText(String.valueOf(v2vB));
            String s = "e^(" + String.valueOf(v2vA) + " - " + String.valueOf(v2vB) + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(4, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("v2", x, y);
            grafic.esRecta(num);
            ++num;
            recalcula();
        }
        //punt LIQUID-SOLID1-SOLID2
        else if (pl1 != 0 && pl2 != 0 && l12t == 0){
            l12t = ((pl1*lv1t) - (pl2*lv2t) + lv2p - lv1p)/(pl1-pl2);
            l12p = pl1*l12t - pl1*lv1t + lv1p;
            grafic.agregarPunt("l12", l12t, l12p);
            grafic.esPunt(num);
            ++num;
            info12l.setText("12L: T = " + String.valueOf(dec.format(l12t)) + " K, P = " + String.valueOf(dec.format(l12p)) + " Pa");
            recalcula();
        }
        //corba SOLID1-SOLID2
        else if (l12t != 0 && v12t != 0 && p12 == 0){
            p12 = (l12p - v12p)/(l12t - v12t);
            String s = String.valueOf(p12) + "*x - " + String.valueOf(p12) + 
                        "*" + String.valueOf(l12t) + " +" + String.valueOf(l12p);
                Funcio f = new Funcio(s);
                double x[] = f.rang(0,1000,0.5);
                double y[] = f.eval(x);
                grafic.agregarGrafic("12", x, y);
                grafic.esRecta(num);
            ++num;
            recalcula();
        }
        //corba LIQUID-SOLID1
        else if (l12t != 0 && lv1t != 0 && pl1 == 0){
            pl1 = (l12p - lv1p)/(l12t - lv1t);
            String s = String.valueOf(pl1) + "*x - " + String.valueOf(pl1) + 
                        "*" + String.valueOf(l12t) + " +" + String.valueOf(l12p);
                Funcio f = new Funcio(s);
                double x[] = f.rang(0,1000,0.5);
                double y[] = f.eval(x);
                grafic.agregarGrafic("l1", x, y);
                grafic.esRecta(num);
            ++num;
            recalcula(); 
        }
        //corba SOLID1-SOLID2
        else if (l12t != 0 && lv2t != 0 && pl2 == 0){
            pl2 = (l12p - lv2p)/(l12t - lv2t);
            String s = String.valueOf(pl2) + "*x - " + String.valueOf(pl2) + 
                        "*" + String.valueOf(l12t) + " +" + String.valueOf(l12p);
                Funcio f = new Funcio(s);
                double x[] = f.rang(0,1000,0.5);
                double y[] = f.eval(x);
                grafic.agregarGrafic("l2", x, y);
                grafic.esRecta(num);
            ++num;
            recalcula(); 
        }
}
    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        double x1 = Double.valueOf(xfrom.getText());
        double x2 = Double.valueOf(xto.getText());
        double y1 = Double.valueOf(yfrom.getText());
        double y2 = Double.valueOf(yto.getText());
        grafic.canviarRang(x1,x2,y1,y2);
    }//GEN-LAST:event_changeActionPerformed

    private void lvlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvlogActionPerformed
        if (lvln.isSelected()) lvln.setSelected(false);
    }//GEN-LAST:event_lvlogActionPerformed

    private void lvlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvlnActionPerformed
        if (lvlog.isSelected()) lvlog.setSelected(false);
    }//GEN-LAST:event_lvlnActionPerformed

    private void lventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lventActionPerformed
        vlvA = Double.valueOf(lvA.getText());
        vlvB = Double.valueOf(lvB.getText());
        if (lvlog.isSelected()){
            if(grafic.existeix("lv1")){
                vlvB = lv1t*vlvA - lv1t*log10(lv1p);
                lvB.setText(String.valueOf(vlvB));
            } else if(grafic.existeix("lv2")){
                vlvB = lv2t*vlvA - lv2t*log10(lv2p);
                lvB.setText(String.valueOf(vlvB));
            }
            String s = "10^(" + lvA.getText() + " - " + lvB.getText() + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(4, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("lv", x, y);
            grafic.esRecta(num);
            ++num;
        } else if (lvln.isSelected()) {
            if(grafic.existeix("lv1")){
                vlvB = lv1t*vlvA - lv1t*log(lv1p);
                lvB.setText(String.valueOf(vlvB));
            } else if(grafic.existeix("lv2")){
                vlvB = lv2t*vlvA - lv2t*log(lv2p);
                lvB.setText(String.valueOf(vlvB));
            }
            String s = "e^(" + lvA.getText() + " - " + lvB.getText() + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(4, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("lv", x, y);
            grafic.esRecta(num);
            ++num;
        }
        recalcula();
    }//GEN-LAST:event_lventActionPerformed

    private void Add1lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1lActionPerformed
            lv1t = Double.valueOf(t1lv.getText());
            t1lv1.setText(t1lv.getText());
            if (lvln.isSelected()) lv1p = exp(vlvA - vlvB/lv1t);
            else if(lvlog.isSelected()) lv1p = pow(10,vlvA - vlvB/lv1t);
            if (v1ln.isSelected()) lv1p = exp(v1vA - v1vB/lv1t);
            else if(v1log.isSelected()) lv1p = pow(10,v1vA - v1vB/lv1t);
            pl1 = Double.valueOf(dpdt1l.getText());
            if (!grafic.existeix("lv1")){
                grafic.agregarPunt("lv1",lv1t,lv1p);
                grafic.esPunt(num);
                ++num;
            }
            info1lv.setText("1LV: T = " + String.valueOf(dec.format(lv1t)) + " K, P = " + String.valueOf(dec.format(lv1p)) + " Pa");
            String s = String.valueOf(pl1) + "*x - " + String.valueOf(pl1) + 
                        "*" + String.valueOf(lv1t) + " +" + String.valueOf(lv1p);
                Funcio f = new Funcio(s);
                double x[] = f.rang(0,1000,0.5);
                double y[] = f.eval(x);
                grafic.agregarGrafic("l1", x, y);
                grafic.esRecta(num);
            ++num;
            recalcula();
    }//GEN-LAST:event_Add1lActionPerformed

    private void Add2lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2lActionPerformed
            lv2t = Double.valueOf(t2lv.getText());
            t2lv1.setText(t2lv.getText());
            if (lvln.isSelected()) lv2p = exp(vlvA - vlvB/lv2t);
            else if(lvlog.isSelected()) lv2p = pow(10,vlvA - vlvB/lv2t);
            if (v2ln.isSelected()) lv2p = exp(v2vA - v2vB/lv2t);
            else if(v2log.isSelected()) lv2p = pow(10,v2vA - v2vB/lv2t);
            pl2 = Double.valueOf(dpdt2l.getText());
            if (!grafic.existeix("lv2")){
                grafic.agregarPunt("lv2",lv2t,lv2p);
                grafic.esPunt(num);
                ++num;
                info2lv.setText("2LV: T = " + String.valueOf(dec.format(lv2t)) + " K, P = "+ String.valueOf(dec.format(lv2p))+ " Pa");
            }
            String s = String.valueOf(pl2) + "*x - " + String.valueOf(pl2) + 
                        "*" + String.valueOf(lv2t) + " +" + String.valueOf(lv2p);
                Funcio f = new Funcio(s);
                double x[] = f.rang(0,1000,0.5);
                double y[] = f.eval(x);
                grafic.agregarGrafic("l2", x, y);
                grafic.esRecta(num);
            ++num;
            recalcula();
    }//GEN-LAST:event_Add2lActionPerformed

    private void Add12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add12ActionPerformed
        
    }//GEN-LAST:event_Add12ActionPerformed

    private void v1logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1logActionPerformed
        if (v1ln.isSelected()) v1ln.setSelected(false);
    }//GEN-LAST:event_v1logActionPerformed

    private void v1lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1lnActionPerformed
        if (v1log.isSelected()) v1log.setSelected(false);
    }//GEN-LAST:event_v1lnActionPerformed

    private void Add1VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1VActionPerformed
        if (!"".equals(v1A.getText())){
            v1vA = Double.valueOf(v1A.getText());
        }
        if (!"".equals(v1B.getText())){
            v1vB = Double.valueOf(v1B.getText());
        }
        if (!"".equals(t12v1.getText())){
            v12t = Double.valueOf(t12v1.getText());
            t12v.setText(String.valueOf(v12t));
            t12v2.setText(String.valueOf(v12t));
        
        }
        if (!"".equals(t1lv1.getText())){
            lv1t = Double.valueOf(t1lv1.getText());
            t1lv.setText(String.valueOf(lv1t));
        }
        if (v1log.isSelected()){
            if (grafic.existeix("v12")){
                v1vB = v12t*v1vA - v12t*log10(v12p);
                v1B.setText(String.valueOf(v1vB));
            } else if(grafic.existeix("lv1")){
                v1vB = lv1t*v1vA - lv1t*log10(lv1p);
                v1B.setText(String.valueOf(v1vB));
            }
            String s = "10^(" + v1A.getText() + " - " + v1B.getText() + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(1, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("v1", x, y);
            grafic.esRecta(num);
            ++num;
            if (lv1t != 0 && !grafic.existeix("lv1")){
                lv1p = pow(10,v1vA - v1vB/lv1t);
                grafic.agregarPunt("lv1", lv1t, lv1p);
                grafic.esPunt(num);
                ++num;
                info1lv.setText("1LV: T = " + String.valueOf(dec.format(lv1t)) + " K, P = " + String.valueOf(dec.format(lv1p)) + " Pa");
            }
            if (v12t != 0 && !grafic.existeix("v12")){
                v12p = pow(10,v1vA - v1vB/v12t);
                grafic.agregarPunt("v12", v12t, v12p);
                grafic.esPunt(num);
                ++num;
                info12v.setText("12V: T = " + String.valueOf(dec.format(v12t)) + " K, P = " + String.valueOf(dec.format(v12p)) + " Pa");
            }
            recalcula();
        } else if (v1ln.isSelected()) {
            if (grafic.existeix("v12")){
                v1vB = v12t*v1vA - v12t*log(v12p);
                v1B.setText(String.valueOf(v1vB));
            } else if(grafic.existeix("lv1")){
                v1vB = lv1t*v1vA - lv1t*log(lv1p);
                v1B.setText(String.valueOf(v1vB));
            }
            String s = "e^(" + v1A.getText() + " - " + v1B.getText() + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(1, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("v1", x, y);
            grafic.esRecta(num);
            ++num;
            if (lv1t != 0 && !grafic.existeix("lv1")){
            lv1p = exp(v1vA - v1vB/lv1t);
            grafic.agregarPunt("lv1", lv1t, lv1p);
            grafic.esPunt(num);
            ++num;
            info1lv.setText("1LV: T = " + String.valueOf(dec.format(lv1t)) + " K, P = " + String.valueOf(dec.format(lv1p)) + " Pa");
            }
            if (v12t != 0 && !grafic.existeix("v12")){
                v12p = exp(v1vA - v1vB/v12t);
                grafic.agregarPunt("v12", v12t, v12p);
                grafic.esPunt(num);
                ++num;
                info12v.setText("12V: T = " + String.valueOf(dec.format(v12t)) + " K, P = " + String.valueOf(dec.format(v12p)) + " Pa");
            }
            recalcula();
        }
    }//GEN-LAST:event_Add1VActionPerformed

    private void Add2VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2VActionPerformed
        if (!"".equals(v2A.getText())){
            v2vA = Double.valueOf(v2A.getText());
        }
        if (!"".equals(v2B.getText())){
            v2vB = Double.valueOf(v2B.getText());
        }
        if (!"".equals(t12v2.getText())){
            v12t = Double.valueOf(t12v2.getText());
            t12v.setText(String.valueOf(v12t));
            t12v1.setText(String.valueOf(v12t));
        
        }
        if (!"".equals(t2lv1.getText())){
            lv2t = Double.valueOf(t2lv1.getText());
            t2lv.setText(String.valueOf(lv2t));
        }
        if (v2log.isSelected()){
            if (grafic.existeix("v12")){
                v2vB = v12t*v2vA - v12t*log10(v12p);
                v2B.setText(String.valueOf(v2vB));
            } else if(grafic.existeix("lv2")){
                v2vB = lv2t*v2vA - lv2t*log10(lv2p);
                v2B.setText(String.valueOf(v2vB));
            }
            String s = "10^(" + v2A.getText() + " - " + v2B.getText() + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(1, 1000, 0.5);
            double y[] = f.eval(x);
            grafic.agregarGrafic("v2", x, y);
            grafic.esRecta(num);
            ++num;
            if (lv2t != 0 && !grafic.existeix("lv2")){
                lv2p = pow(10,v2vA - v2vB/lv2t);
                grafic.agregarPunt("lv2", lv2t, lv2p);
                grafic.esPunt(num);
                ++num;
                info2lv.setText("2LV: T = " + String.valueOf(dec.format(lv2t)) + " K, P = "+ String.valueOf(dec.format(lv2p))+ " Pa");
            }
            if (v12t != 0 && !grafic.existeix("v12")){
                v12p = pow(10,v2vA - v2vB/v12t);
                grafic.agregarPunt("v12", v12t, v12p);
                grafic.esPunt(num);
                ++num;
                info12v.setText("12V: T = " + String.valueOf(dec.format(v12t)) + " K, P = " + String.valueOf(dec.format(v12p)) + " Pa");
            }
            recalcula();
        } else if (v2ln.isSelected()) {
            if (grafic.existeix("v12")){
                v2vB = v12t*v2vA - v12t*log(v12p);
                v2B.setText(String.valueOf(v2vB));
            } else if(grafic.existeix("lv2")){
                v2vB = lv2t*v2vA - lv2t*log(lv2p);
                v2B.setText(String.valueOf(v2vB));
            }
            String s = "e^(" + v2A.getText() + " - " + v2B.getText() + "/x)";
            Funcio f = new Funcio(s);
            double x[] = f.rang(1, 1000, 0.5);
            double y[] = f.eval(x);           
            grafic.agregarGrafic("v2", x, y);
            grafic.esRecta(num);
            ++num;
            if (lv2t != 0 && !grafic.existeix("lv2")){
                lv2p = exp(v2vA - v2vB/lv2t);
                grafic.agregarPunt("lv2", lv2t, lv2p);
                grafic.esPunt(num);
                ++num;
                info2lv.setText("2LV: T = " + String.valueOf(dec.format(lv2t)) + " K, P = "+ String.valueOf(dec.format(lv2p))+ " Pa");
            }
            if (v12t != 0 && !grafic.existeix("v12")){
                v12p = exp(v2vA - v2vB/v12t);
                grafic.agregarPunt("v12", v12t, v12p);
                grafic.esPunt(num);
                ++num;
                info12v.setText("12V: T = " + String.valueOf(dec.format(v12t)) + " K, P = " + String.valueOf(dec.format(v12p)) + " Pa");
            }
            recalcula();
        }
    }//GEN-LAST:event_Add2VActionPerformed

    private void v2logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2logActionPerformed
        if (v2ln.isSelected()) v2ln.setSelected(false);
    }//GEN-LAST:event_v2logActionPerformed

    private void v2lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2lnActionPerformed
        if (v2log.isSelected()) v2log.setSelected(false);
    }//GEN-LAST:event_v2lnActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        grafic.logy();
    }//GEN-LAST:event_logActionPerformed

    private void linActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linActionPerformed
        grafic.lin();
    }//GEN-LAST:event_linActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interficie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interficie().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add12;
    private javax.swing.JButton Add1V;
    private javax.swing.JButton Add1l;
    private javax.swing.JButton Add2V;
    private javax.swing.JButton Add2l;
    private javax.swing.JButton change;
    private javax.swing.JTextField dpdt12;
    private javax.swing.JTextField dpdt1l;
    private javax.swing.JTextField dpdt2l;
    private javax.swing.JLabel info12l;
    private javax.swing.JLabel info12v;
    private javax.swing.JLabel info1lv;
    private javax.swing.JLabel info2lv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton lin;
    private javax.swing.JButton log;
    private javax.swing.JTextField lvA;
    private javax.swing.JTextField lvB;
    private javax.swing.JButton lvent;
    private javax.swing.JRadioButton lvln;
    private javax.swing.JRadioButton lvlog;
    private javax.swing.JPanel panel;
    private javax.swing.JButton restart;
    private javax.swing.JTextField t12v;
    private javax.swing.JTextField t12v1;
    private javax.swing.JTextField t12v2;
    private javax.swing.JTextField t1lv;
    private javax.swing.JTextField t1lv1;
    private javax.swing.JTextField t2lv;
    private javax.swing.JTextField t2lv1;
    private javax.swing.JLabel titol;
    private javax.swing.JTextField v1A;
    private javax.swing.JTextField v1B;
    private javax.swing.JRadioButton v1ln;
    private javax.swing.JRadioButton v1log;
    private javax.swing.JTextField v2A;
    private javax.swing.JTextField v2B;
    private javax.swing.JRadioButton v2ln;
    private javax.swing.JRadioButton v2log;
    private javax.swing.JTextField xfrom;
    private javax.swing.JTextField xto;
    private javax.swing.JTextField yfrom;
    private javax.swing.JTextField yto;
    // End of variables declaration//GEN-END:variables
    Grafic grafic = new Grafic("","T","P");
}
